[package]
name = "lampe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noirc_driver = { path = "../noir/compiler/noirc_driver" }
noirc_frontend = { path = "../noir/compiler/noirc_frontend" }
nargo = { path = "../noir/tooling/nargo" }

itertools = "0.12.1"