[package]
name = "Dependencies"
type = "bin"
authors = [""]

[dependencies]
ecrecover = { tag = "v0.30.0", git = "https://github.com/colinnielsen/ecrecover-noir" }
easy_private_token_contract = { tag ="v0.1.0-alpha62", git = "https://github.com/AztecProtocol/aztec-packages", directory = "yarn-project/noir-contracts/src/contracts/easy_private_token_contract" }
local_dependency = { path = "/home/piotr/Workspace/Reilabs/lampe/Examples/LocalDependency" }

