name: CI on Noir test programs
on:
  workflow_dispatch:
jobs:
    run-tests:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout Noir repo
            uses: actions/checkout@v4
            with:
              repository: noir-lang/noir
              path: noir
          - name: Set up Rust
            uses: actions-rs/toolchain@v1
          - name: Build (cargo)
            working-directory: noir
            run: cargo build --release
          - name: Install (cargo)
            working-directory: noir
            run: cargo install --path .
          - name: Ensure test programs up-to-date
            working-directory: noir/test_programs
            run: ./rebuild.sh
          - name: Checkout Lampe repo
            uses: actions/checkout@v4
            with:
              path: lampe
          - name: Set up Rust
            uses: actions-rs/toolchain@v1
          - name: Build (cargo)
            working-directory: lampe
            run: cargo build --release
          - name: Install (cargo)
            working-directory: noir
            run: cargo install --path .
          - name: Set up Lean 4
            uses: leanprover/lean-action@v1
            with:
              auto-config: false
              build: false
              test: false
              lint: false
              use-mathlib-cache: true
              lake-package-directory: lampe/Lampe
          - name: Run Lampe on each test_program
            working-directory: lampe/noir_testing
            run: ./test.sh --noir-path ${{ github.workspace }}
